baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Multilevel Navigation"

[menu]
# Category 1
[[menu.main]]
  identifier = 'category-1'
  name = 'Category 1'
  title = 'Category 1'
  url = '/category-1/'
  weight = 1
[[menu.main]]
  identifier = 'sub-category-1a'
  name = 'Sub-category A'
  title = 'Sub-category A'
  url = '/category-1/sub-category-a/'
  weight = 1
  parent = 'category-1'
[[menu.main]]
  identifier = 'sub-category-1b'
  name = 'Sub-category B'
  title = 'Sub-category B'
  url = '/category-1/sub-category-b/'
  weight = 2
  parent = 'category-1'
[[menu.main]]
  identifier = 'sub-category-1c'
  name = 'Sub-category C'
  title = 'Sub-category C'
  url = '/category-1/sub-category-c/'
  weight = 3
  parent = 'category-1'

# Category 2
[[menu.main]]
  identifier = 'category-2'
  name = 'Category 2'
  title = 'Category 2'
  url = '/category-2/'
  weight = 2
[[menu.main]]
  identifier = 'sub-category-2a'
  name = 'Sub-category A'
  title = 'Sub-category A'
  url = '/category-2/sub-category-a/'
  weight = 1
  parent = 'category-2'
[[menu.main]]
  identifier = 'sub-category-2b'
  name = 'Sub-category B'
  title = 'Sub-category B'
  url = '/category-2/sub-category-b/'
  weight = 2
  parent = 'category-2'
[[menu.main]]
  identifier = 'sub-category-2c'
  name = 'Sub-category C'
  title = 'Sub-category C'
  url = '/category-2/sub-category-c/'
  weight = 3
  parent = 'category-2'

# Category 3
[[menu.main]]
  identifier = 'category-3'
  name = 'Category 3'
  title = 'Category 3'
  url = '/category-3/'
  weight = 3
[[menu.main]]
  identifier = 'sub-category-3a'
  name = 'Sub-category A'
  title = 'Sub-category A'
  url = '/category-3/sub-category-a/'
  weight = 1
  parent = 'category-3'
[[menu.main]]
  identifier = 'sub-category-3b'
  name = 'Sub-category B'
  title = 'Sub-category B'
  url = '/category-3/sub-category-b/'
  weight = 2
  parent = 'category-3'
[[menu.main]]
  identifier = 'sub-category-3c'
  name = 'Sub-category C'
  title = 'Sub-category C'
  url = '/category-3/sub-category-c/'
  weight = 3
  parent = 'category-3'

# Sub-category A Items
[[menu.main]]
  identifier = 'item-1'
  name = 'Item 1'
  title = 'Item 1'
  url = '/category-1/sub-category-a/item-1'
  weight = 1
  parent = 'sub-category-1a'
[[menu.main]]
  identifier = 'item-2'
  name = 'Item 2'
  title = 'Item 2'
  url = '/category-2/sub-category-a/item-2'
  weight = 2
  parent = 'sub-category-1a'
[[menu.main]]
  identifier = 'item-3'
  name = 'Item 3'
  title = 'Item 3'
  url = '/category-3/sub-category-a/item-3'
  weight = 3
  parent = 'sub-category-1a'